# 2025 Week-1 Homework

## Q1. Pandas version

In [63]:
import pandas as pd
import numpy as np

In [64]:
pd.__version__

'2.3.1'

## Getting the Car Fuel Efficiency dataset from the downloaded csv file

In [65]:
df = pd.read_csv("01-Intro/car_fuel_efficiency.csv")
df.head() # confirm data is read into the dataset

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## Q2. Records count - How many records are in the dataset?

In [66]:
len(df)

9704

## Q3. - Fuel types: How many fuel types are presented in the dataset?

In [67]:
df["fuel_type"].nunique()

2

## Q4. Missing values: How many columns in the dataset have missing values?

In [68]:
null_in_series = df.isnull().sum()
series_with_nulls = (null_in_series > 0).sum()
print(series_with_nulls)

4


## Q5. Max fuel efficiency: What's the maximum fuel efficiency of cars from Asia?

In [69]:
Asian_cars_df = df["origin"] == "Asia"
print(df[Asian_cars_df]["fuel_efficiency_mpg"].max())

23.759122836520497


## Q6. Median value of horsepower

#### 1. Find the median value of horsepower column in the dataset.

In [70]:
print(df.horsepower.median())

149.0


#### 2. Next, calculate the most frequent value of the same horsepower column

In [97]:
freq_hp_df = df['horsepower'].mode()[0]
freq_hp_df

np.float64(152.0)

#### 3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.

In [98]:
df['horsepower'].fillna(freq_hp_df,inplace=True)

In [106]:
df.head(20)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                   170            3.0       159.0     3413.433759   
1                   130            5.0        97.0     3149.664934   
2                   170            NaN        78.0     3079.038997   
3                   220            4.0       152.0     2542.392402   
4                   210            1.0       140.0     3460.870990   
5                   190            3.0       152.0     2484.883986   
6                   240            7.0       127.0     3006.542287   
7                   150            4.0       239.0     3638.657780   
8                   250            1.0       174.0     2714.219310   
9                   150            4.0       123.0     3509.036569   
10                  230            5.0       100.0     3111.810181   
11                  150            5.0       152.0     1967.200421   
12                  320            5.0       145.0     2783.868974   
13                  170            1.0       193.0     2274.735191   
14                  200            6.0       160.0     3582.687368   
15                  220            4.0       179.0     2631.065204   
16                  160            3.0       180.0     2673.552941   
17                  190            6.0       132.0     2427.311856   
18                  250            2.0       110.0     2971.214575   
19                  180            1.0       126.0     2986.958657   

    acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0           17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1           17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2           15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3           20.2        2009     USA    Diesel    All-wheel drive        2.0   
4           14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
5           14.7        2008  Europe  Gasoline    All-wheel drive       -1.0   
6           22.2        2012     USA  Gasoline  Front-wheel drive        1.0   
7           17.3        2020     USA    Diesel    All-wheel drive        1.0   
8           10.3        2016    Asia    Diesel  Front-wheel drive       -1.0   
9           10.2        2005     USA  Gasoline  Front-wheel drive       -1.0   
10          15.4        2014  Europe    Diesel    All-wheel drive        0.0   
11          12.6        2014     USA    Diesel  Front-wheel drive        2.0   
12          15.1        2010    Asia    Diesel    All-wheel drive        1.0   
13          17.5        2000  Europe    Diesel  Front-wheel drive        0.0   
14          14.9        2007    Asia    Diesel    All-wheel drive        0.0   
15          16.0        2006     USA  Gasoline    All-wheel drive        1.0   
16           8.5        2013  Europe    Diesel    All-wheel drive       -1.0   
17          17.8        2011     USA    Diesel  Front-wheel drive       -1.0   
18           NaN        2003  Europe  Gasoline  Front-wheel drive        1.0   
19          17.9        2004  Europe  Gasoline    All-wheel drive       -1.0   

    fuel_efficiency_mpg  
0             13.231729  
1             13.688217  
2             14.246341  
3             16.912736  
4             12.488369  
5             17.271818  
6             13.210412  
7             12.848884  
8             16.823554  
9             12.298355  
10            13.386605  
11            20.504447  
12            16.175820  
13            18.792742  
14            11.871091  
15            16.756081  
16            17.516176  
17            17.658685  
18            14.735962  
19            15.097137

In [102]:
print(df.horsepower.median())

152.0


### Q7. Sum of weights

#### Select all the cars from Asia

In [121]:
pd_asia = df[df['origin'] == 'Asia'][['vehicle_weight','model_year']].head(7)
pd_asia

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [119]:
X = pd_asia.to_numpy()

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [127]:
XT= X.T
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [129]:
XTX = XT.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [130]:
np.linalg.inv(XTX)

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])