# Vector Operation

In [2]:
import numpy as np

In [12]:
u = np.array([2, 4, 5, 6])
u

array([2, 4, 5, 6])

In [33]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [6]:
print (u + v)

[3 4 5 8]


# Vector Multiplication (Dot Multiplication)

In [8]:
print (u * v) 

[ 2  0  0 12]


In [10]:
u.transpose()

array([2, 4, 5, 6])

In [54]:
def vector_vector_multiply(u, v):
    assert u.shape[0] == v.shape[0]

    n= u.shape[0]
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [14]:
print(vecto_Vector_multiply(u, v))

14.0


In [17]:
print(u.dot(v)) # The Numpy dot operator implementation of the above

14


In [26]:
print(U.shape[1])

4


# Matrix - Vector Multiplication

In [28]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [55]:
def matrix_vector_multiply(U,v):
    assert U.shape[1] == v.shape[0] # Confirm that the number of rows in matrix matches the number of column in the vector

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiply(U[i], v)
        print("Iteration ", i)
    return result


In [56]:
matrix_vector_multiply(U,v)

Iteration  0
Iteration  1
Iteration  2


array([14.,  5.,  5.])

In [57]:
U.dot(v) # Numpy does the same with the dot operator

array([14,  5,  5])

# Matrix-Matrix Multiplication

In [58]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [59]:
def matrix_matrix_multiply(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows,num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiply(U, vi)
        result[:, i] = Uvi
    return result

matrix_matrix_multiply(U, V)
        

Iteration  0
Iteration  1
Iteration  2
Iteration  0
Iteration  1
Iteration  2
Iteration  0
Iteration  1
Iteration  2


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [60]:
U.dot(V) # The Numpy dot operator implementation of the above

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identity Matrix

In [66]:
I = np.eye(3)

In [67]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

# Inverse

In [78]:
V_square = V[[0, 1, 2]] # Take the 1st, 2nd and the 3rd rows from the V matrix to get a square matrix
V_square

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [83]:
V_square_inverse = np.linalg.inv(V_square)
V_square_inverse

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [85]:
V_square_inverse.dot(V_square) # 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])