In [2]:
import numpy as np

# Creating Arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,4,6,8,4,7]) # passing a list to numpy
a

array([1, 2, 4, 6, 8, 4, 7])

In [7]:
print(a[2]) # accessing the 3rd element

4


In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(1,6,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8])

In [10]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Multi-dimension Arrays

In [11]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [13]:
print(n[0][2]) # Or print(n[0,2])

3


In [14]:
n[0, 2] = 20 # Update a roww element

In [15]:
n

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [40]:
print(n[:,2]) # Or  Print the 3rd column

[20 13  9]


In [41]:
print(n[2]) # Or  Print the 3rd row

[7 8 9]


In [42]:
n[1] = [11, 12, 13] # Update the 2nd row
n

array([[ 1,  2, 20],
       [11, 12, 13],
       [ 7,  8,  9]])

In [43]:
n.transpose()

array([[ 1, 11,  7],
       [ 2, 12,  8],
       [20, 13,  9]])

# Randomly generated arrays

In [19]:
np.random.rand(5,2)

array([[0.52825934, 0.08434982],
       [0.54383289, 0.86614177],
       [0.1290484 , 0.71579708],
       [0.1006333 , 0.34719729],
       [0.19118675, 0.16819674]])

In [20]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [21]:
np.random.randn(5,2) # Random normal distribution

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [22]:
100*np.random.rand(5,2) # Random number between 0 and 100

array([[42.81223276,  9.65309157],
       [12.71599717, 59.6745309 ],
       [22.60120006, 10.69456843],
       [22.03062071, 34.9826285 ],
       [46.77874846, 20.17432263]])

In [23]:
np.random.randint(low=0, high=100, size=(5,2)) # @-dimensional integer array between low and high numbers

array([[15,  8],
       [17, 22],
       [73, 57],
       [90, 62],
       [83, 96]])

# Element-wise operations

In [24]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [25]:
a + 1 # Numpy makes this easy, otherwise we will loop the list

array([1, 2, 3, 4, 5])

In [26]:
a * 2 # Same comment as above

array([0, 2, 4, 6, 8])

In [27]:
a/10

array([0. , 0.1, 0.2, 0.3, 0.4])

In [28]:
b = (10 + (a * 2)) ** 2/100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [29]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

# Comparison Operations

In [30]:
a >= 2

array([False, False,  True,  True,  True])

In [31]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [32]:
a > b

array([False, False,  True,  True,  True])

In [33]:
a[a > b] # returns all elements of array, a for which the condition is true

array([2, 3, 4])

# Summarising Operations

In [34]:
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

0
4
2.0
1.4142135623730951


In [35]:
print(n.max()) # Print the maximum element of a a-dimension array above

20


In [36]:
print(n.std()) # Print the standard deviation of a a-dimension array above

5.452375176171243
